---

- hosts: all
  remote_user: "{{ user }}"

  vars_files:
    - vars/main.yml

  roles:
    - name: essentials
      tags: essentials

    - name: timezone
      tags: timezone

    - name: iptables
      tags: iptables
      when: inventory_hostname != 'localhost'

    - name: fail2ban
      tags: fail2ban
      when: inventory_hostname != 'localhost'

    - name: certbot
      tags: ssl
      when: inventory_hostname != 'localhost' and configure_certbot

    - name: ssl
      tags: ssl
      when: inventory_hostname != 'localhost' and configure_ssl

    - name: nodejs
      tags: nodejs
      become: true

    - name: nginx
      tags: nginx
      become: true

    - name: ufw
      tags: ufw
      become: true

    - name: php
      tags: php
      become: true

    - name: composer
      tags: composer

    - name: mysql
      tags: mysql
      become: true

    - name: redis
      tags: redis
      become: true

  tasks:
    - name: Create base directory
      file:
        path: "{{ domain_path }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0711
      become: true
      tags: setup_deploy
