---

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present
  become: true

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'
  become: true

- name: Create a new regular user with sudo privileges
  user:
    name: "{{ user }}"
    #password: "{{ password }}"
    state: present
    groups: wheel
    append: true
    create_home: true
    shell: /bin/bash
  become: true

- name: Add ssh key for new super user
  authorized_key:
    user: "{{ user }}"
    key: "{{ lookup('file', public_key) }}"
  become: true
