---

- name: Ensure ssh is installed
  apt:
    pkg: openssh-server
    state: latest
    update_cache: true
    cache_valid_time: 3600

- name: Disable root login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  become: true
  notify: Restart ssh

#- name: Disable password authentication for root
#  lineinfile:
#    path: /etc/ssh/sshd_config
#    state: present
#    regexp: '^#?PermitRootLogin'
#    line: 'PermitRootLogin prohibit-password'

- name: Disable password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  become: true
  notify: Restart ssh

- name: Only allow ssh access for the newly created user
  lineinfile:
    dest: /etc/ssh/sshd_config
    insertafter: "^StrictModes"
    line: "AllowUsers {{ user }}"
    state: present
  become: true
  notify: Restart ssh
