---

- name: Ensure UFW is installed
  apt:
    name: ufw
    state: latest
    update_cache: yes
  become: true

- name: Enable UFW firewall
  ufw:
    state: enabled
  become: true

- name: Set default policy to deny all incoming traffic
  ufw:
    direction: incoming
    policy: deny
  become: true

- name: Allow SSH with rate limiting
  ufw:
    rule: limit
    port: ssh
    proto: tcp
  become: true

- name: Allow HTTP
  ufw:
    rule: allow
    port: http
    proto: tcp
  become: true

- name: Allow HTTPS
  ufw:
    rule: allow
    port: https
    proto: tcp
  become: true
