---

# PHP Related tasks goes here
- name: Install PHP {{ php_version }} PPA Repository
  apt_repository:
    repo: 'ppa:ondrej/php'

- name: Update APT cache
  apt:
    update_cache: yes
  become: true

- name: Install PHP {{ php_version }}
  apt:
      pkg: "{{ item }}"
      state: present
      update_cache: yes
  with_items:
    - php{{ php_version }}-dev
    - php{{ php_version }}-cli
    - php{{ php_version }}-fpm
    - php{{ php_version }}-curl
    - php{{ php_version }}-gd
    - php{{ php_version }}-imagick
    - php{{ php_version }}-imap
    - php{{ php_version }}-intl
    - php{{ php_version }}-mbstring
    - php{{ php_version }}-mysql
    - php{{ php_version }}-pgsql
    - php{{ php_version }}-sqlite3
    - php{{ php_version }}-xml
    - php{{ php_version }}-zip
    - php{{ php_version }}-json
    - php{{ php_version }}-bcmath
    - php{{ php_version }}-tokenizer
    - php{{ php_version }}-opcache
    - php{{ php_version }}-redis
    - php{{ php_version }}-apcu
    - composer
  notify:
    - Start php-fpm
  become: true

# Configure PHP.
- include_tasks: configure.yml
- include_tasks: configure-apcu.yml
- include_tasks: configure-opcache.yml
- include_tasks: configure-fpm.yml
